title: Travis Gorman
email: theFarBetween@me.com
description: > # this means to ignore newlines until "baseurl:"
  Front End JavaScript Developer
baseurl: ""
url: "http://yourdomain.com" 
twitter_username: thefarbetween
github_username:  travisgorman

permalink: /:categories/:title
links:
    - title: about
      url: /about
    - title: work
      url: /work
    - title: articles
      url: /articles
    - title: hire me
      url: /hire-me

# Build settings
markdown: kramdown
